### ISSUE TITLE
caro60.csv and pedestrian.csv missing

### ISSUE THREAD

**Issue by ratnanil** [mariottomarina/cma-week3#1]
https://github.com/mariottomarina/cma-week3/blob/3ec318987d9fb2fdd215ccbb3e7da1cc327abc27/week3_rexercise.R#L9-L9<br/><br/>and

https://github.com/mariottomarina/cma-week3/blob/3ec318987d9fb2fdd215ccbb3e7da1cc327abc27/week3_rexercise.R#L150-L151

Can you commit and ~~add~~ push `caro60.csv` as well as `pedestrian.csv` so I can run the code locally? Same as 

https://github.com/mariottomarina/cma-week2/issues/7
https://github.com/mariottomarina/cma-week2/issues/2

and https://github.com/RicardaFerrari/cma-exercise3/issues/1

**Comment by mariottomarina** [comment]
The .csv files are now available in the repo.

**Comment by ratnanil** [comment]
perfect, thank you!
